site_name: Arista CVP collection
site_author: Arista Ansible Team
site_description: Arista Cloudvision collection's documentation
docs_dir: ansible_collections/arista/cvp/
site_favicon: docs/_media/favicon.ico
theme:
  name: material
  features:
    - instant
  highlightjs: true
  hljs_languages:
        - yaml
        - python
        - shell
extra_css:
  - docs/stylesheets/extra.material.css
copyright: Copyright &copy; 2019 - 2020 Arista Networks
repo_name: CVP on Github
repo_url: https://github.com/aristanetworks/ansible-cvp
use_directory_urls: true
nav:
  - Home: README.md
  - Getting Started: docs/getting-started.md
  - Installation:
    - Requirements: docs/installation/requirements.md
    - Configure your local environment: docs/installation/setup-environement.md
    - Installation using git: docs/installation/setup-git.md
    - Installation using ansible-galaxy: docs/installation/setup-galaxy.md
    - Docker & Development: docs/installation/setup-docker.md
  - How-To:
    - Configure Cloudvision Authentication: docs/how-to/cvp-authentication.md
  - Roles documentation:
    - DHCP Configuration role: roles/dhcp_configuration/README.md
    - Cloudvision Configlet Sync: roles/configlets_sync/README.md
  - Modules documentation:
    - Module cv_facts: docs/modules/cv_facts.rst.md
    - Module cv_configlet: docs/modules/cv_configlet.rst.md
    - Module cv_container: docs/modules/cv_container.rst.md
    - Module cv_device: docs/modules/cv_device.rst.md
    - Module cv_tasks: docs/modules/cv_task.rst.md
  - External resources:
    - Ansible collection user guide: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html
    - Ansible User guide: https://docs.ansible.com/ansible/latest/user_guide/index.html
  - About:
    - Ansible Galaxy page: https://galaxy.ansible.com/arista/cvp
    - Arista Validated Design Collection: https://www.avd.sh
    - Arista Automation Examples: https://aristanetworks.github.io/netdevops-examples/

markdown_extensions:
  - smarty
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - fontawesome_markdown
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      separator: "-"
      permalink: "#"
      baselevel: 1
