site_name: Arista CVP collection
site_author: Arista Ansible Team
site_description: Arista Cloudvision collection's documentation
docs_dir: ansible_collections/arista/cvp/
site_favicon: docs/_media/favicon.ico
theme:
  name: material
  features:
    - navigation.instant
    # - toc.integrate
  highlightjs: true
  hljs_languages:
        - yaml
        - python
        - shell
extra_css:
  - docs/stylesheets/extra.material.css
copyright: Copyright &copy; 2019 - 2021 Arista Networks
repo_name: CV Collection on Github
repo_url: https://github.com/aristanetworks/ansible-cvp
use_directory_urls: true

plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      type: date

markdown_extensions:
  - mdx_truly_sane_lists
  - smarty
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - fontawesome_markdown
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      separator: "-"
      # permalink: "#"
      permalink: true
      baselevel: 3
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: 'ansible_collections/arista/cvp/'

nav:
  - Home: README.md
  - Getting Started: docs/getting-started.md
  - Release Notes:
    - Versions 1.x: docs/release-notes/v1.x.md
    - Versions 2.x: docs/release-notes/v2.x.md
    - Versions 3.x: docs/release-notes/v3.x.md
  - Installation:
    - Requirements: docs/installation/requirements.md
    - Configure your local environment: docs/installation/setup-environement.md
    - Installation using git: docs/installation/setup-git.md
    - Installation using ansible-galaxy: docs/installation/setup-galaxy.md
    - Docker & Development: docs/installation/setup-docker.md
  - How-To:
    - CV Authentication: docs/how-to/cvp-authentication.md
    - CV Modules v1:
      - Get Facts: docs/how-to/v1/cv_facts.md
      - Manage configlets: docs/how-to/v1/cv_configlet.md
      - Manage containers: docs/how-to/v1/cv_container.md
      - Manage devices: docs/how-to/v1/cv_device.md
    - CV Modules v3:
      - Manage configlets: docs/how-to/v3/cv_configlet_v3.md
      - Manage containers: docs/how-to/v3/cv_container_v3.md
      - Manage devices: docs/how-to/v3/cv_device_v3.md
    - Development tips & tricks: docs/installation/development.md
    - Activate logging: docs/how-to/debug.md
  - Frequently Asked Questions:
    - Error Messages: docs/faq/errors.md
  - Roles documentation:
    - DHCP Configuration role: roles/dhcp_configuration/README.md
    - Cloudvision Configlet Sync: roles/configlets_sync/README.md
  - Modules documentation:
    - Modules version 1:
      - Module cv_facts: docs/modules/cv_facts.rst/
      - Module cv_configlet: docs/modules/cv_configlet.rst/
      - Module cv_container: docs/modules/cv_container.rst/
      - Module cv_device: docs/modules/cv_device.rst/
      # - Module cv_task: docs/modules/cv_task.rst/
    - Module version 3:
      - Module cv_configlet_v3: docs/modules/cv_configlet_v3.rst.md
      - Module cv_container_v3: docs/modules/cv_container_v3.rst.md
      - Module cv_device_v3: docs/modules/cv_device_v3.rst.md
      - Module cv_task_v3: docs/modules/cv_task_v3.rst.md
  - External resources:
    - Ansible collection user guide: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html
    - Ansible User guide: https://docs.ansible.com/ansible/latest/user_guide/index.html
  - About:
    - Ansible Galaxy page: https://galaxy.ansible.com/arista/cvp
    - Arista Validated Design Collection: https://www.avd.sh
    - Arista Automation Examples: https://aristanetworks.github.io/netdevops-examples/
