# Project information
site_name: Arista CVP collection
site_author: Arista Ansible Team
site_description: Arista CloudVision collection's documentation
copyright: Copyright &copy; 2019 - 2022 Arista Networks

# Repository
repo_name: CV Collection on Github
repo_url: https://github.com/aristanetworks/ansible-cvp

# Configuration
use_directory_urls: true
edit_uri: edit/devel/ansible_collections/arista/cvp/
theme:
  name: material
  custom_dir: ansible_collections/arista/cvp/docs/_overrides
  features:
    - navigation.instant
    - navigation.top
    - search.highlight
    - header.autohide
    - content.code.annotate
    - content.tabs.link
  highlightjs: true
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/book
    edit: fontawesome/solid/file-pen
  favicon: docs/_media/favicon.ico
  font:
    code: Fira Mono
  language: en
  include_search_page: false
  search_index_only: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aristanetworks/ansible-cvp
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AristaNetworks
    - icon: fontawesome/solid/globe
      link: https://www.arista.com

extra_css:
  - docs/stylesheets/extra.material.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - docs/stylesheets/tables.js

plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      type: date
  # Deactivated due to https://github.com/tikitu/jsmin/issues/33
  # Issue in progress: https://github.com/byrnereese/mkdocs-minify-plugin/issues/15
  # - minify:
  #     minify_html: true
  #     minify_js: true

markdown_extensions:
  - admonition
  - attr_list
  - mdx_truly_sane_lists
  - smarty
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.snippets:
      base_path: 'ansible_collections/arista/cvp/'
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      separator: "-"
      # permalink: "#"
      permalink: true
      baselevel: 3

# TOC
docs_dir: ansible_collections/arista/cvp/
nav:
  - Home: README.md
  - Getting Started: docs/getting-started.md
  - Installation:
    - Collection Installation: docs/installation/collection-installation.md
    - Requirements: docs/installation/requirements.md
  - How-To:
    - CV Authentication: docs/how-to/cvp-authentication.md
    - CV Modules v1:
      - Get Facts: docs/how-to/v1/cv_facts.md
      - Manage configlets: docs/how-to/v1/cv_configlet.md
      - Manage containers: docs/how-to/v1/cv_container.md
      - Manage devices: docs/how-to/v1/cv_device.md
    - CV Modules v3:
      - Manage configlets: docs/how-to/v3/cv_configlet_v3.md
      - Manage containers: docs/how-to/v3/cv_container_v3.md
      - Manage devices: docs/how-to/v3/cv_device_v3.md
      - Manage images & bundles: docs/how-to/v3/cv_image_v3.md
      - Manage tasks: docs/how-to/v3/cv_task_v3.md
      - Manage tags: docs/how-to/v3/cv_tag_v3.md
      - Manage change control: docs/how-to/v3/cv_change_control_v3.md
      - Validate Configlets: docs/how-to/v3/cv_validate_v3.md
      - Get facts from CloudVision: docs/how-to/v3/cv_facts_v3.md
    - Development tips & tricks: docs/installation/collection-installation.md
    - Activate logging: docs/how-to/debug.md
  - Schema documentation:
    - CV Modules v3:
      # - cv_configlet_v3: docs/schema/cv_tag_v3.md
      - cv_container_v3: docs/schema/cv_container_v3.md
      - cv_device_v3: docs/schema/cv_device_v3.md
      # - cv_task_v3: docs/schema/cv_task_v3.md
      # - cv_facts_v3: docs/schema/cv_facts_v3.md
      # - cv_image_v3: docs/schema/cv_image_v3.md
      - cv_tag_v3: docs/schema/cv_tag_v3.md
      - cv_change_control_v3: docs/schema/cv_change_control_v3.md
      - cv_validate_v3: docs/schema/cv_validate_v3.md
  - Frequently Asked Questions:
    - Error Messages: docs/faq/errors.md
    - Ansible Execution Environment: docs/faq/containers.md
  - Roles documentation:
    - DHCP Configuration role: roles/dhcp_configuration/README.md
    - CloudVision Configlet Sync: roles/configlets_sync/README.md
  - Modules documentation:
    - Modules version 1:
      - cv_facts: docs/modules/cv_facts.md
      - cv_configlet: docs/modules/cv_configlet.md
      - cv_container: docs/modules/cv_container.md
      - cv_device: docs/modules/cv_device.md
      - cv_task: docs/modules/cv_task.md
    - Module version 3:
      - cv_configlet_v3: docs/modules/cv_configlet_v3.md
      - cv_container_v3: docs/modules/cv_container_v3.md
      - cv_device_v3: docs/modules/cv_device_v3.md
      - cv_task_v3: docs/modules/cv_task_v3.md
      - cv_facts_v3: docs/modules/cv_facts_v3.md
      - cv_image_v3: docs/modules/cv_image_v3.md
      - cv_tag_v3: docs/modules/cv_tag_v3.md
      - cv_change_control_v3: docs/modules/cv_change_control_v3.md
      - cv_validate_v3: docs/modules/cv_validate_v3.md
  - External resources:
    - Ansible collection user guide: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html
    - Ansible User guide: https://docs.ansible.com/ansible/latest/user_guide/index.html
  - Release Notes:
    - Versions 1.x: docs/release-notes/v1.x.md
    - Versions 2.x: docs/release-notes/v2.x.md
    - Versions 3.x: docs/release-notes/v3.x.md
  - About:
    - Ansible Galaxy page: https://galaxy.ansible.com/arista/cvp
    - Arista Validated Design Collection: https://www.avd.sh
    - Arista Automation Examples: https://aristanetworks.github.io/netdevops-examples/
