galaxy_info:
  author: Arista Ansible Team <ansible@arista.com>
  description: Role to configure DHCP service to act as ZTP server
  issue_tracker_url: https://github.com/aristanetworks/ansible-cvp/issues
  company: Arista Networks
  license: Apache-2.0
  min_ansible_version: 2.9
  galaxy_tags: ['arista', 'network', 'networking', 'eos', 'avd', 'cloudvision', 'cvp']
  platforms:
    - name: EL
      versions: [7, 8]
  dependencies: []
