name: Commit check
on:
  push:
  pull_request:
jobs:
  'pre-commit':
    name: Run pre-commit validation hooks
    runs-on: ubuntu-latest
    container: avdteam/base:3.6
    steps:
      - uses: actions/checkout@v2
      - name: test pre-commit
        run: |
          pip --no-cache-dir install -r development/requirements-dev.txt
          pre-commit help
      - name: 'Pre Commit run'
        run: |
          make pre-commit
