name: Collection Publication
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  local_build:
    name: Build Ansible CVP Collection
    runs-on: ubuntu-latest
    container: avdteam/base:centos-8
    steps:
      - uses: actions/checkout@master

      - name: 'Ansible Galaxy build'
        run: |
          make collection-build
          ls -al
          mkdir artifacts/
          mv *.tar.gz artifacts

      - uses: actions/upload-artifact@v1
        with:
          name: ansible-cvp-${{env.RELEASE_VERSION}}
          path: './artifacts/'
